name: sise
description: "Suivi Evaluation."

publish_to: 'none' 

version: 2.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  move_to_background: ^1.0.2
  odoo_rpc: ^0.5.4
  path_provider: ^2.1.3
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  connectivity_plus: ^5.0.2
  http: ^1.2.2
  intl: ^0.19.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  flutter_localization: ^0.2.0
  flutter_launcher_icons: ^0.13.1
  pull_to_refresh: ^2.0.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/sise.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
